### ISSUE TITLE
When using a field through a Ref it does not allow adding aliases to the field

### ISSUE THREAD

**Issue by coffeeniac** [ordnaelmedeiros/jpa-fluid-select#11]
When I add return fields using the fields () method, it does not allow me to add aliases to this field. The need for this is why I need to return another name that matches my DTO.

Example:

![image](https://user-images.githubusercontent.com/53283796/75155585-279d1580-56ef-11ea-8e43-f6961880dfd3.png)

I verified that it is only possible to add an alias if the return field is not through a Ref.

How can I solve this?

**Comment by ordnaelmedeiros** [comment]
Change your code like this reference:
https://github.com/ordnaelmedeiros/jpa-fluid-select#customfieldstransform

In short, use getSingleResultByConstructor(YourDTO.class) and code constructor or change the field selector:
```java
    .field(joinUsuario.field(Usuario_.id)).alias("usuarioId")
```
